apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  serviceName: echoserver
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: echoserver
        image: ghcr.io/mwennrich/echoserver:latest
        ports:
        - containerPort: 8090
          name: echo
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
